"""Mapping from short/raw feature names to descriptive standardized names."""
feature_rename_map = {
    "chunk": "chunk",
    "inst_dist_m_sum": "instantaneous_distance_meters_sum",
    "Speed (m/s)_mean": "speed_meters_per_second_mean",
    "hsr_m_sum": "high_speed_running_meters_sum",
    "vha_count_1s_sum": "vertical_high_acceleration_count_1_second_sum",
    "avg_jerk_1s_mean": "average_jerk_1_second_mean",
    "turns_per_sec_sum": "turns_per_second_sum",
    "playerload_1s_sum": "player_load_1_second_sum",
    "walk_time_sum": "walk_time_sum",
    "jog_time_sum": "jog_time_sum",
    "run_time_sum": "run_time_sum",
    "sprint_time_sum": "sprint_time_sum",
    "total_sprints_sum": "total_sprints_sum",
    "sprint_attack_sum": "sprint_attack_sum",
    "sprint_defense_sum": "sprint_defense_sum",
    "dist_attack_sum": "distance_attack_sum",
    "dist_defense_sum": "distance_defense_sum",
    "time_attack_sum": "time_attack_sum",
    "time_defense_sum": "time_defense_sum",
    "attacking_third_time_sum": "attacking_third_time_sum",
    "middle_third_time_sum": "middle_third_time_sum",
    "defending_third_time_sum": "defending_third_time_sum"
}
