"""Feature column names used for physical modeling and preprocessing."""
FEATURE_COLUMNS = [
    "minute",
    "inst_dist_m_sum",
    "Speed (m/s)_mean",
    "Speed (m/s)_max",
    "hsr_m_sum",
    "vha_count_1s_sum",
    "avg_jerk_1s_mean",
    "turns_per_sec_sum",
    "playerload_1s_sum",
    "walk_time_sum",
    "jog_time_sum",
    "run_time_sum",
    "sprint_time_sum",
    "accel_decel_balance_attack_last",
    "accel_decel_balance_defense_last",
    "total_sprints_sum",
    "sprint_attack_sum",
    "sprint_defense_sum",
    "dist_attack_sum",
    "dist_defense_sum",
    "time_attack_sum",
    "time_defense_sum",
    "time_defending_sec",
    "time_middle_sec",
    "time_attacking_sec"
]